---
- name: my ansible playbook
  hosts: 127.0.0.1
  vars_files:
   - group_vars/vault.yml
  tasks:    
    - name: print secure variable
      debug: msg="my secure variable= \n{{ ssh_priv }}"

    - name: test node name file
      ansible.builtin.debug:
        msg: "{{ ansible_nodename }}"

    - name: test conditional
      ansible.builtin.debug:
        msg: "{% if system_hosts is defined %}{% for key, value in system_hosts.items() %}{{ key }} {{ value }}\n{% endfor %}{% endif %}"