---
- name: my ansible playbook
  hosts: 127.0.0.1
  ansible.builtin.include_vars:
    dir: global_vars/
  tasks:    
    - name: print secure variable
      debug: msg="my secure variable= \n{{ ssh_priv }}"