---
- name: my ansible playbook
  hosts: 127.0.0.1
  vars_files:
   - group_vars/vault.yml
  tasks:    
    - name: print secure variable
      debug: msg="my secure variable= \n{{ ssh_priv }}"

    - name: test host file
      ansible.builtin.debug:
        msg: "{{ ansible_nodename }}"